# Generated by Django 2.1.7 on 2019-03-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starnavi_blog_api', '0002_auto_20190318_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Post likes'),
        ),
    ]
