# Generated by Django 2.1.7 on 2019-03-18 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('starnavi_blog_api', '0003_auto_20190318_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date and Time Created'),
            preserve_default=False,
        ),
    ]
