# Generated by Django 2.1.7 on 2019-03-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starnavi_blog_api', '0005_auto_20190319_2109'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlikes',
            unique_together=set(),
        ),
    ]
